# Generated by Django 4.0.4 on 2022-05-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sumary',
            new_name='summary',
        ),
    ]
